-- Add LOST movement type
ALTER TYPE "MovementType" ADD VALUE IF NOT EXISTS 'LOST';

-- Add LOST workflow statuses
ALTER TYPE "MovementStatus" ADD VALUE IF NOT EXISTS 'DEPT_APPROVED';
ALTER TYPE "MovementStatus" ADD VALUE IF NOT EXISTS 'COST_CONTROL_APPROVED';
ALTER TYPE "MovementStatus" ADD VALUE IF NOT EXISTS 'FINANCE_APPROVED';
ALTER TYPE "MovementStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
